### ISSUE TITLE
Broken since last Atom update

### ISSUE THREAD

**Issue by mrleblanc101** [haklop/touchbar-registry#2]
Hi,
The plugin seem to be broken since Atom 1.23
I have the linter-ui-touchbar plugin and I see the icon appearing on startup but by the time Atom finish initializing, the icon disappear and I'm left with a bunch of empty button in the Touch Bar (see screenshot). Disabling and re-enabling touchbar-registery seem to fix the problem but only for the current session.
<img width="1085" alt="capture d ecran touch bar 2018-01-21 a 20 34 09" src="https://user-images.githubusercontent.com/17392251/35201587-beac8730-feea-11e7-8606-074b306670cb.png">
<img width="1085" alt="capture d ecran touch bar 2018-01-21 a 20 36 52" src="https://user-images.githubusercontent.com/17392251/35201605-d8cc4dbc-feea-11e7-9871-fdd5b80127f1.png">

**Comment by phyllisstein** [comment]
Seeing the same thing through 1.25.0-beta2. The touchbar appears when the window, but as soon as the editor focus changes the controls vanish.

**Comment by Xapphire13** [comment]
Doesn't seem to repro on atom `1.35.1`
